services:
  app_container:
    image: python:3.11
    hostname: app_container
    env_file:
      - app.env
      - db.env
    stdin_open: true
    tty: true
    links:
      - db_container
    depends_on:
      - db_container

  db_container:
    image: postgres:14.8
    hostname: db_container
    env_file:
      - db.env
